/* EMIC roster — edit this file to update people anywhere on the site.
   photo: paste a Wix Media Manager URL (or any hosted image URL). Leave '' for a placeholder.
   objectPosition / scale: optional per-photo crop controls, e.g. 'center 30%', 1.3 */

const BOARD = [
  { name: 'Matthew Jarek', role: 'Co-President', photo: 'assets/matt.JPG', major: 'J.D. Candidate', year: 2029, email: 'mj638@cornell.edu', research: 'Demographics and Population Based Macro Trends', involvement: 'URF, IM Basketball and Soccer, Society of Polish Students', professional: 'M&A Law', favoriteEM: 'Mexico', funFact: 'I trained ITF Taekwondo for 15 years' },
  { name: 'Thomas Riveros', role: 'Co-President', photo: 'https://static.wixstatic.com/media/8812e8_d4a838a5e437407a893b569378c91a02~mv2.jpg', major: 'Economics', year: 2027, email: 'tmr94@cornell.edu', research: "Bolivia's Economic Crisis: lessons on Resource Dependence and Fiscal Sustainability; Gasoline Shortages and the Return of Inflation in Bolivia", involvement: 'Cru Cornell', professional: 'Wealth Management, Economic Research', favoriteEM: 'Bolivia', funFact: 'I am an avid runner and have logged over 1000 miles on Strava' },
  { name: 'Aashay Mody', role: 'Treasurer', photo: 'https://static.wixstatic.com/media/8812e8_894ef435baca4098acb216b6f510c997~mv2.png', major: 'Environment & Sustainability', year: 2028, email: 'am3497@cornell.edu', research: "Fiji's Blue Bond a Means of Sustainable Investment; Evaluating the Effectiveness of the Seychelles Blue Bond", involvement: 'Cornell Sustainability Consultants, Science Olympiad at Cornell, Cornell University Student Assembly, Cornell International Affairs Society', professional: 'Innovative Conservation and Sustainability Finance', favoriteEM: 'Costa Rica', funFact: 'I can play the viola, enjoy birding, and have been vegan for over 6 years.' },
  { name: 'Sasha Kasher', role: 'Frontier Minute', photo: 'assets/Sasha.jpeg', major: 'History & Government', year: 2029, email: 'abk239@cornell.edu', research: 'Physical infrastructure management and supply chain research', involvement: 'Russian Language Society, Lambda Chi Alpha Fraternity', professional: 'Foreign Trade Relations', favoriteEM: 'Caspian region (Kazakhstan, Kyrgyzstan, Uzbekistan)', funFact: 'Before college, I interned in Kazakhstan, where I translated and researched commodity markets' },
  { name: 'Daniel Young Kim', role: 'Beating Sisyphus', photo: 'https://static.wixstatic.com/media/8812e8_c20c3d74dd604ce9b75260531d0ce5b7~mv2.jpg', objectPosition: 'center 30%', major: 'Applied Economics and Management', year: 2028, email: 'dyk36@cornell.edu', research: "Government's role in their local economies (or lack thereof)", involvement: 'EMC2, State Policy Advocacy Clinic, Project Hope, KKR Scholar', professional: 'Commercial Litigation (Distressed Situations) | Civil Rights Law', favoriteEM: 'Thailand', funFact: 'Talk to me about F1 or Pokemon and we will be great friends' },
  { name: 'Anastasiia Ryshytiuk', role: 'Research', photo: 'https://static.wixstatic.com/media/8812e8_c3a02ca8ecfd4c0eaaf31f6fe37a3ac7~mv2.jpg', major: 'Urban and Regional Studies', year: 2028, email: 'ar2529@cornell.edu', research: 'International development and the ways policy, institutions, and foreign investment interact to foster more equitable and resilient societies in emerging economies and post-conflict settings. Previous research on digital governance, foreign aid, and sustainable finance.', involvement: 'International Students Association VP; Collegetown Magazine; Einaudi Global Scholar; Salsa; IIC', professional: 'Institution-building and social justice in international development and post-conflict recovery.', favoriteEM: 'Ghana', funFact: 'I once got stranded on a deserted island overnight with some friends.' },
  { name: 'Erin Baek', role: 'Recruitment', photo: 'assets/erin.jpeg', major: 'Biometry & Statistics and Global Development', year: 2028, email: 'eab378@cornell.edu', research: 'Agrochemical Regulation and Governance in the Global South', involvement: '—', professional: 'Health economics, development economics, pharma/biotech', favoriteEM: 'Vietnam, India, China', funFact: 'I once snorkeled with sharks (and stepped on one) in San Diego' },
  { name: 'Jeremy Chen', role: 'Recruitment', photo: 'https://static.wixstatic.com/media/8812e8_9001a05321164f96be025c8b9bc9e1a0~mv2.jpg', major: 'Economics', year: 2029, email: 'yc2944@cornell.edu', research: 'Cross-border M&A', involvement: 'Impact Investing, Cornell Christian Business Club, Taiwanese American Student Association', professional: 'ESG Finance', favoriteEM: 'Malaysia', funFact: 'I grew up in Taiwan, build computers and Gunpla. My favorite artist is Lady Gaga' },
  { name: 'William Earls', role: 'Social', photo: 'assets/will.JPG', major: 'Global Development', year: 2029, email: 'wge9@cornell.edu', research: 'Evaluating Indian Semiconductor Manufacturing: An Investment Pitch for CG Power; Renewable Resources in Bhutan', involvement: 'Cornell Commodity Trading Club, Cornell Beef Cattle Club, Club Water Polo, Humphrey Fellow PCAT', professional: 'Consulting in international economics/EM', favoriteEM: 'Kyrgyzstan', funFact: 'My interest in emerging markets stemmed from writing a letter to the Dentist turned former leader of Turkmenistan, Gurbanguly Berdimuhamedow.' },
  { name: 'Matthew Lee', role: 'NME & Senior Chair', photo: 'https://static.wixstatic.com/media/8812e8_947e09f847224dacb091b3340ec171cc~mv2.png', major: 'Economics', year: 2027, email: 'mjl373@cornell.edu', research: 'Oil Money Digitized: The Role of Private Investment in Fintech Development in the United Arab Emirates, Through Time; The African Middle-Class and their Equities Market', involvement: 'Phi Alpha Delta Pre-law Frat, Alexander Hamilton Society, Cornell Rugby', professional: 'Investment banking, Geopolitics', favoriteEM: 'Brazil', funFact: 'I am studying abroad right now!' },
  { name: 'Josh Feinburg', role: 'NME & Senior Chair', photo: 'https://static.wixstatic.com/media/8812e8_1de4950f2c4d40a8b747c54a2f445f71~mv2.png', major: 'Environmental Economics', year: 2027, email: 'jmf398@cornell.edu', research: 'Revamping Debt-for-Nature Swaps: A Holistic Assessment of Fiscal and Environmental Effectiveness in Latin America; Power and Infrastructure in South East Asia, Green and Blue Bonds in South America', involvement: 'Impact Investing at Cornell, Delta Phi', professional: 'Securitized Products, Project Finance, Impact Finance, Distressed Debt, Green Bonds', favoriteEM: 'Ecuador', funFact: 'I have visited 30+ countries!' },
  { name: 'Vivian Lei', role: 'NME & Senior Chair', photo: 'https://static.wixstatic.com/media/8812e8_bbed7774f26d4fa19e9841a06ece03b6~mv2.png', major: 'Industrial and Labor Relations', year: 2027, email: 'vl338@cornell.edu', research: 'Outlook on Argentinian Sovereign Bonds; Chinese Securitized SMEs Loans as Alternative Funding Solutions; Private Markets', involvement: 'Global Cornell Connection, Cayuga Capital, Cornell Diplomat, Global Business Club', professional: 'Banking, Structured Products, Private Credit', favoriteEM: 'Russia', funFact: 'I like watching 3+ hour video essays' },
  { name: 'Konrad Hartung', role: 'NME & Senior Chair', photo: 'https://static.wixstatic.com/media/8812e8_c7ee8321595d45e4a3497e2d5f0b5dbc~mv2.png', major: 'Economics & College Scholar', year: 2028, email: 'kfh37@cornell.edu', research: 'The Global Middle Class; The Social Costs of Serial Restructurings', involvement: 'Cornell Equity Research, Consult Your Community, International Student Association, Robert S. Harrison College Scholar', professional: 'Restructuring, Credit, Macroeconomic Policy', favoriteEM: 'India', funFact: 'I love tea!' },
  { name: 'Siddhi Wakdikar', role: 'NME & Senior Chair', photo: 'assets/siddhi.jpg', major: 'MPS in Applied Statistics; Computer Science', year: 2026, email: 'smw356@cornell.edu', research: 'Renewable Energy Infrastructure Development in India', involvement: 'Society of Women Engineers, Women in Computing at Cornell', professional: 'Software Engineering, Data Science', favoriteEM: 'India', funFact: 'I got my black belt in Taekwondo at 9' },
  { name: 'Sea Phongsphetrarat', role: 'Operations Chair', photo: 'https://static.wixstatic.com/media/8812e8_4b9fc8d483c7482d82968474feadac24~mv2.png', major: 'Hotel Administration', year: 2028, email: 'pp535@cornell.edu', research: 'Comparing the viability of private equity and private credit investments within India and Singapore', involvement: 'Cornell Fashion Collective, Cornell University Autonomous Underwater Vehicle, Cornell Thai Association', professional: 'Investment Banking', favoriteEM: 'Thailand', funFact: 'I like film and photography!' },
  { name: 'Star Kim', role: 'Operations Chair', photo: 'assets/Star.jpg', major: 'Government', year: 2028, email: 'bk482@cornell.edu', research: 'How fintech, digital assets, and retail investing are changing access to capital and wealth creation in emerging economies; how emerging economies design AI regulation when they are primarily adopters rather than producers of frontier AI', involvement: 'Global Cornell Connection; M&A Club; Business Club of Emerging Economies; Agua Clara Engineering Project Team', professional: 'Banking; Corporate Law; International Law', favoriteEM: 'Brazil', funFact: 'I love Celsius!' },
  { name: 'Fiorina Siamir', role: 'Operations Chair', photo: 'https://static.wixstatic.com/media/8812e8_c7f63834cda9495497177a073ffe1a42~mv2.jpg', major: 'Industrial and Labor Relations', year: 2028, email: 'fas78@cornell.edu', research: "Indonesia's QRIS and the Architecture of Regional Payment Sovereignty", involvement: 'Rawlings Presidential Research Scholar, Cañizares Center for Emerging Markets, Society for Women in Business, Indonesian Association at Cornell', professional: '', favoriteEM: 'Indonesia', funFact: 'I can bake a fire blueberry muffin' }
];

const MEMBERS = [
  { name: 'Linh Le', major: 'Finance (VinUniversity)', year: 2027, photo: 'https://static.wixstatic.com/media/8812e8_077d91febb3942679d767897dd65a2cf~mv2.png', email: '23linh.ln@vinuni.edu.vn', research: 'AI Automation, Higher Education Development Strategy, Workplace Culture', involvement: '—', professional: 'Management Consulting, Real Estate Investment', favoriteEM: 'Vietnam, India, China', funFact: "I keep mental notes of all my friends' drink orders :)" },
  { name: 'Amy Park', major: 'Applied Economics and Management', year: 2027, photo: 'https://static.wixstatic.com/media/8812e8_00ac075cb42c453899856ad9b2ce8eb8~mv2.jpg', email: 'yp489@cornell.edu', research: 'Comparing the viability of private equity and private credit investments within India and Singapore through 2017-2025', involvement: 'Delta Sigma Pi', professional: '—', favoriteEM: 'Indonesia', funFact: 'I have been to 10+ countries!' },
  { name: 'Oleguer Marine', major: 'Finance', year: 2027, photo: 'https://static.wixstatic.com/media/8812e8_e9169e779b6b40798e7451d451e22056~mv2.png', email: 'om237@cornell.edu', research: 'SPAC', involvement: 'Cornell Latinos In Business, Scholars of Finance, Cornell Bitcoin Club, Cornell Commodity Trading Club', professional: 'Wealth Management', favoriteEM: 'China', funFact: "I've been to three different continents in just two weeks" },

  { name: 'Amanda Palmer', major: 'Global Development', year: 2028, photo: 'https://static.wixstatic.com/media/8812e8_2df078ebfbb94b1fb279a17ef0a1fd6c~mv2.png', email: 'Aip36@cornell.edu', research: "Impact of geopolitics in EM's, ESG investing in EM's, Development Economics and Tech", involvement: 'The Advocacy Project, Spanish Speech and Debate', professional: 'Nonprofit Consulting, Impact Evaluations Analyst', favoriteEM: 'Indonesia', funFact: "I'm from Venezuela and Spanish is my first language!" },
  { name: 'Kevyn Gunawan', major: 'Industrial and Labor Relations', year: 2028, photo: 'https://static.wixstatic.com/media/8812e8_6c45560f76c446aea2540185f062c89e~mv2.png', email: 'krg78@cornell.edu', research: 'Beyond the Final Whistle: The Post-Event Economics of World Cup Hosting in Emerging Markets; Geopolitics, Southeast Asia, Migrant Workers, Sports', involvement: 'International Students Association, Cornell Club Squash, Singapore Student Association, Indonesians at Cornell, ILR Global Affairs Club, Cornell International Affairs Review', professional: 'Emerging Market Strategy, Global Finance', favoriteEM: 'Indonesia', funFact: 'I can name every country in the world.' },
  { name: 'Louis Philippe Jansen', major: 'Industrial and Labor Relations', year: 2028, photo: 'https://static.wixstatic.com/media/8812e8_7b8f37ffeca64d378571e623e4ac50c8~mv2.png', email: 'ljj43@cornell.edu', research: 'Belt and Road Initiative (BRI) and its regional economic impacts; cross-border investment flows in Asia; development trajectories in Asian regions; U.S. trade and investment engagement with Asia.', involvement: 'International Business Consulting', professional: 'Consulting, Financial Services, and Economic Development', favoriteEM: 'China', funFact: 'I transferred from Duke Kunshan University my sophomore year.' },
  { name: 'Martin Revelo', major: 'Economics', year: 2028, photo: 'https://static.wixstatic.com/media/8812e8_2d8c78cef63d429abb15b545b1d3065a~mv2.png', email: 'mer329@cornell.edu', research: "Bolivia's lithium sector and the political economy constraints limiting EM growth", involvement: "Cornell Men's Polo Team, Emerging Markets Institute Club, BlackGen Capital, ALPFA Cornell", professional: 'Finance, Market Research, Banking', favoriteEM: 'Ecuador', funFact: "I walked into Cornell's Men's Polo Team this fall." },
  { name: 'Maya Hamandi', major: 'Global Development', year: 2028, photo: 'https://static.wixstatic.com/media/8812e8_cdf8707dafa248cd9b2ddab1a56225b1~mv2.png', email: 'mzh9@cornell.edu', research: 'Examining Market Reactions to Petrobras-Related Events', involvement: 'Cornell Rowing Club, Cornell Media Guild, Cornell Speech and Debate', professional: 'International Finance, Banking', favoriteEM: 'Qatar', funFact: 'I love to scuba dive!' },
  { name: 'Novi Chen', major: 'Economics', year: 2028, photo: 'https://static.wixstatic.com/media/8812e8_5d10b1b9947b44a2981d86660d08c2e5~mv2.jpg', email: 'nc573@cornell.edu', research: 'Development Economics, Macroeconomics; Corruption as an Urgent Development Constraint in Vietnam — Evidence from the Truong My Lan Case', involvement: 'Society of Women in Business', professional: 'Economic Consulting', favoriteEM: 'Vietnam', funFact: 'My name is Novi because I was born in November' },
  { name: 'Logan Clappier', major: 'Economics and History', year: 2028, photo: 'https://static.wixstatic.com/media/8812e8_097c4041f71b439aa133c815d96a8c66~mv2.jpg', email: '', research: 'Statecraft and Frontier Tech Formation Indices', involvement: 'Commodities Trading Club, SAFC, Sprint Football', professional: 'Geopolitics and Tech', favoriteEM: '', funFact: 'You can find me sailing Cayuga Lake on the weekends' },
  { name: 'Rachel Bataille', major: 'Public Policy', year: 2028, photo: 'https://static.wixstatic.com/media/8812e8_15aaa9c6406c41789abea4a42723e94f~mv2.png', email: 'rlb423@cornell.edu', research: 'Examining Market Reactions to Petrobras-Related Events', involvement: 'Brooks School Ambassador & Peer Mentor, Society for Women in Business, Cornell Institute of Politics and Global Affairs, Cornell Class Councils, Cornell Panhellenic Council', professional: 'Economic Policy, Trade Policy', favoriteEM: 'Argentina', funFact: "I grew up learning three languages besides English — and somehow can't speak any of them." },
  { name: "Jean D'Amour", major: 'Economics & Data Science', year: 2028, photo: 'https://static.wixstatic.com/media/8812e8_2134f4a5998a4f98a4b9a88a13903e1e~mv2.png', email: 'jm2876@cornell.edu', research: 'Financial access and credit constraints for micro and small enterprises in emerging markets, with a focus on credit guarantee schemes, microfinance impact evaluation, and firm-level growth in Sub-Saharan Africa and South Asia.', involvement: "Impact Investing at Cornell (IIC), Cornell Rotaract, CU Vita, Club Soccer, Salsa Pa'lante, Cornell Computer Reuse Association (CCRA), Empower Them (Founder)", professional: 'Capital markets and investment in emerging economies, development finance, and deploying capital toward sustainable economic growth in frontier markets.', favoriteEM: 'Rwanda', funFact: 'My first name is actually "Jean D\'Amour" — which translates to "John of Love" in French.' },
  { name: 'Prajwal Reddy', major: 'Computer Science and Linguistics', year: 2028, photo: 'https://static.wixstatic.com/media/8812e8_12aaae15c27d4797bc06eb8ad2b12d75~mv2.png', email: 'pmr93@cornell.edu', research: 'Intersection between tech, culture, and socioeconomic development', involvement: 'Federal Reserve Club, UnderLings, Computational Imaging Lab @ Cornell, CU Sail, COE', professional: 'Technology, Finance, Research', favoriteEM: 'India', funFact: 'I have a business card collection with over 800 cards from all over the world.' },

  { name: 'Annette Hoi Ching Jap', major: 'Applied Economics and Management', year: 2029, photo: 'https://static.wixstatic.com/media/8812e8_eee116d8682f4428a3c6db80ecd585a7~mv2.jpg', email: 'aj683@cornell.edu', research: 'Consumption trend in China, Generative AI and its implications on developing economies', involvement: 'SEGC, COGDOG', professional: 'Consulting, finance', favoriteEM: 'China', funFact: 'I can do a Mexican wave with my eyebrows' },
  { name: 'Mario Antonaccio', major: 'Economics and Mathematics', year: 2029, photo: 'https://static.wixstatic.com/media/8812e8_b2bd93f4ba9c497da5c83930f99a2c46~mv2.png', email: 'mea258@cornell.edu', research: 'Foreign Direct Investments, Foreign Portfolio Investments', involvement: 'Banking at Cornell, Milstein Program, Business Club for Emerging Economies', professional: 'Finance, Banking', favoriteEM: 'China', funFact: 'I have broken my right arm three times' },
  { name: 'William Glasser', major: 'Engineering', year: 2029, photo: 'https://static.wixstatic.com/media/8812e8_7b40d3076b3f483b8fed7a49c2ad5d8a~mv2.png', email: 'whg49@cornell.edu', research: 'Currency Restrictions', involvement: 'Steel Bridge Project Team (Construction, welding, design subteams), Big Red Sports Network (Softball announcer)', professional: 'Consulting, materials science and engineering', favoriteEM: 'Argentina', funFact: 'I caddied for two professional golfers at the 2025 Osprey Valley Open' },
  { name: 'Calista Chang', major: 'Industrial and Labor Relations', year: 2029, photo: 'https://static.wixstatic.com/media/8812e8_88a957867d7e400590208a71eafd0b9a~mv2.png', email: 'cc2858@cornell.edu', research: "How India's Cashless Payment Ecosystem Built a Revenue Generating UPI Model, with a Focus on Credit and Subscription Based Cross-Selling", involvement: 'ASSAT, APPS, Club Tennis', professional: 'Equity Research', favoriteEM: 'Thailand', funFact: 'I love incline walking.' },
  { name: 'Lisa Huynh', major: 'Applied Economics and Management', year: 2029, photo: 'https://static.wixstatic.com/media/8812e8_22f09a329cbf419cac13ed2ec7294cd4~mv2.png', email: 'hh822@cornell.edu', research: 'AI and Automation', involvement: 'A Seat At a Table, Cornell Marketing Club', professional: 'Consulting and Brand Management', favoriteEM: 'China and Thailand', funFact: 'China and Thailand' },
  { name: 'Ava Murdock', major: 'Economics and Public Policy', year: 2029, photo: 'https://static.wixstatic.com/media/8812e8_5aa192b889f64e6da7698a0d74fe64ac~mv2.png', email: 'acm367@cornell.edu', research: 'FDI', involvement: 'Cornell Orchestras, Cornell Votes, and Language Corners (French)', professional: 'Municipal or international law.', favoriteEM: 'Kenya', funFact: 'I read 41 books in 2025' },
  { name: 'Michael Chen', major: 'Economics', year: 2029, photo: 'https://static.wixstatic.com/media/8812e8_a06b1ecf03ec42f59799022ca4b61803~mv2.png', email: 'mc2986@cornell.edu', research: 'Semiconductors, tech, international trade', involvement: 'Cornell Wall Street Club, Cornell Business Review, Cornell Speech and Debate Society', professional: 'Basketball, Debate', favoriteEM: 'China', funFact: "I was present when LeBron broke Kareem's scoring record, and I bought the tickets for just 50 bucks 5 months prior to the game." },
  { name: 'Kelly Huang', major: 'Human Biology, Health, and Society', year: 2029, photo: 'https://static.wixstatic.com/media/8812e8_f2454b417bb34b1ebe268fe7b8dd4be6~mv2.png', email: 'zh498@cornell.edu', research: 'Healthcare policy and global health economics', involvement: 'Social Enterprise Group at Cornell', professional: 'Strategy Consulting', favoriteEM: 'China', funFact: 'I genuinely like Okenshields, which I know may be a hot take.' },
  { name: 'Victor Blanchard', major: 'Industrial and Labor Relations', year: 2029, photo: 'https://static.wixstatic.com/media/8812e8_37d19daa4d5641fa83de9c28c0ca2261~mv2.png', email: 'vab64@cornell.edu', research: 'AI in Southeast Asia', involvement: 'Cornell Financial Analysts, Cornell Alpha Fund, and Global Cornell Connection', professional: 'Investment Banking, Venture Capital', favoriteEM: 'Vietnam', funFact: 'I was a foreign exchange student in Hangzhou, China' },
  { name: 'Camille Parisot', major: 'Economics and Government', year: 2029, photo: 'https://static.wixstatic.com/media/8812e8_b0e2642d5afe4b68801067f4c7c8d780~mv2.png', email: 'cap364@cornell.edu', research: "Chinese Foreign Direct Investment in Zambia's Energy and Mining Sectors; FDI Impact on Economic Growth and Development in Angola", involvement: 'Zambia Community Education Initiative, Cornell Undergraduate Research Board, International Students Association, Einhorn Center POST Leader, Cornell Daily Sun Photographer', professional: 'Development Economics, Macroeconomic Policy', favoriteEM: 'Saudi Arabia', funFact: 'I am a photographer and love to travel' }
];

/* Beating Sisyphus page team (subset with circular treatment handled by page) */
const BS_TEAM = [
  { name: 'Anastasiia Ryshytiuk', major: 'Urban and Regional Studies, Class of 2028', photo: 'https://static.wixstatic.com/media/8812e8_c3a02ca8ecfd4c0eaaf31f6fe37a3ac7~mv2.jpg' },
  { name: 'Thomas Riveros', major: 'Economics, Class of 2027', photo: 'https://static.wixstatic.com/media/8812e8_d4a838a5e437407a893b569378c91a02~mv2.jpg' },
  { name: 'Daniel Young Kim', major: 'Applied Economics and Management, Class of 2028', photo: 'https://static.wixstatic.com/media/8812e8_c20c3d74dd604ce9b75260531d0ce5b7~mv2.jpg', objectPosition: 'center 40%' },
  { name: 'Konrad Hartung', major: 'Economics & College Scholar, Class of 2028', photo: 'https://static.wixstatic.com/media/8812e8_c7ee8321595d45e4a3497e2d5f0b5dbc~mv2.png' },
  { name: 'Lourdes Casanova', major: 'Director of the Cañizares Center for Emerging Markets', photo: 'https://static.wixstatic.com/media/8812e8_1dcc99a80dbd4ef896bbdcd64cfb0918~mv2.jpg' },
  { name: 'Linh Le', major: 'Finance, Class of 2027, VinUniversity', photo: 'https://static.wixstatic.com/media/8812e8_077d91febb3942679d767897dd65a2cf~mv2.png', scale: 1.4 }
];
